// for questions
export const CREATE_QUESTION_REQUEST = 'CREATE_QUESTION_REQUEST';
export const CREATE_QUESTION_SUCCESS = 'CREATE_QUESTION_SUCCESS';
export const CREATE_QUESTION_FAILURE = 'CREATE_QUESTION_FAILURE';

export const GET_QUESTIONS_REQUEST = 'GET_QUESTIONS_REQUEST';
export const GET_QUESTIONS_SUCCESS = 'GET_QUESTIONS_SUCCESS';
export const GET_QUESTIONS_FAILURE = 'GET_QUESTIONS_FAILURE';

// for batches
export const FETCH_BATCHES_REQUEST = 'FETCH_BATCHES_REQUEST';
export const FETCH_BATCHES_SUCCESS = 'FETCH_BATCHES_SUCCESS';
export const FETCH_BATCHES_FAILURE = 'FETCH_BATCHES_FAILURE';
export const CREATE_BATCH_SUCCESS = 'CREATE_BATCH_SUCCESS';
export const JOIN_BATCH_SUCCESS = 'JOIN_BATCH_SUCCESS';

// for the login 
export const  LOGIN_REQUEST =  'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
// for the register 
export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';
// logout 
export const LOGOUT_USER = 'LOGOUT_USER';
// export const LOAD_TOKEN = 'LOAD_TOKEN';

// answers
export const CREATE_ANSWER_REQUEST = 'CREATE_ANSWER_REQUEST';
export const CREATE_ANSWER_SUCCESS = 'CREATE_ANSWER_SUCCESS';
export const CREATE_ANSWER_FAILED = 'CREATE_ANSWER_FAILED'

export const GET_ANSWER_REQUEST = 'GET_ANSWER_REQUEST';
export const GET_ANSWER_SUCCESS = 'GET_ANSWER_SUCCESS';
export const GET_ANSWER_FAILED = 'GET_ANSWER_FAILED'


// for updates in database
export const QUESTION_ANSWER_UPDATED = 'QUESTION_ANSWER_UPDATED';
export const USER_STATS_UPDATED = 'USER_STATS_UPDATED';
export const  CLEAR_ANSWERS = 'CLEAR_ANSWERS';

export const FETCH_JOINED_BATCHES_SUCCESS = 'FETCH_JOINED_BATCHES_SUCCESS';

